config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  get 'home/about'
  get 'home/post'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_one_attached :photo
   
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  # def aboutus
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:post_name, :description, :photo, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
    <header>
  <nav class="navbar navbar-expand-lg">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="toggle-navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbar-content">
        <ul class="navbar-nav">
        <% if user_signed_in? %>
        <%= link_to 'Home', root_path, class:"nav-link"%>
          <%= link_to 'About', home_about_path, class:"nav-link"%>
           <%= link_to 'Posts', posts_path, class:"nav-link"%>
           <%= link_to 'Sign Out', destroy_user_session_path,method: :delete, class:"nav-link"%>
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
            <% else %>
              <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="box">
        <div class="box-1"></div>
        <div class="box-2"></div>
      </div>
    </header>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>index</h1>

app/views/home/post.html.erb
posts

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
 

 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  


    <title>Rails app</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<%= render 'home/header'%>
<div class="container">

 <%= yield %> 
 </div>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :post_name , class:"form-label" %>
    <%= form.text_field :post_name,class:"form-control" %>
  </div>

  <div class="field">
  <%= form.label :post_description , class:"form-label" %>
    <%= form.text_field :description,class:"form-control" %>
  </div>
  <br>
  <div class="form-control">
 
  <% if post.photo.attached? %>
    <image src="<%= (url_for(@post.photo))%>" style="width: 200px; height: 200px;">
       <%end%>
       <br>
     <%= form.label :photo , class:"form-label" %>
    <%= form.file_field :photo, class:"form-control"%>  
  </div>
  <div class="field">
    <%= form.number_field :user_id, id: :post_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

<br>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
  <br>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead class="text-center">
    <tr >
      <th scope="col">Post name</th>
      <th scope="col">Description</th>
      <th scope="col">Photo</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody class="text-center">
    <tr>
     <% @posts.each do |post| %>
      <td><%= post.post_name %></td>
      <td><%= post.description %></td>
      <td> <image src="<%= (url_for(post.photo))%>" width="100" height="100" style="border-radius: 50%; width: 30px; height: 30px;"></td>
      <td><%= link_to 'Show', post, class:"btn btn-primary"%> 
      <%= link_to 'Edit', edit_post_path(post), class:"btn btn-success"%>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
    </tr>
        <% end %>
     </tbody>
</table>

<br>
<%= link_to 'New Post', new_post_path, class:"btn btn-secondary" %>





<%
=begin%>
 
<table>
  <thead>
    <tr>
      <th>Post name</th>
      <th>Description</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.post_name %></td>
        <td><%= post.description %></td>
        <td><%= post.photo %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> 
<%
=end%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:"btn btn-primary"%>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h1 class="display-4"><%= @post.post_name %></h1>
    <p class="lead"><%= @post.description %></p>
    
    <image src="<%= (url_for(@post.photo))%>" style="border-radius: 50%; width: 200px; height: 200px;">
 
  </div>
  <br>
  <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-primary"%>
<%= link_to 'Back', posts_path, class:"btn btn-success" %>
</div>